---

- hosts: localhost

  gather_facts: no

  vars: 
    DEST_PATH: /tmp/test_dir

  tasks:

   - name: create dest folder
     file:
       path: "{{ DEST_PATH }}"
       state: directory
       mode: 0755
     
   - name: copy script
     copy: 
       src: files/delete_cwd.sh
       dest: "{{ DEST_PATH }}/delete_cwd.sh"
       mode: 0755

#sh: 0: getcwd() failed: No such file or directory
#('[powerline-bash] ', 'Your current directory is invalid. Lowest valid directory: /tmp')

   - name: run script - which deletes the cwd and thus fails
     shell: ./delete_cwd.sh
     args:
      chdir: "{{ DEST_PATH }}"


